=== hrist0stoichev/Telerik-Homeworks/Databases/XML Basics/students.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="students"
    targetNamespace="http://webdude.eu/students.xsd"
    elementFormDefault="qualified"
    xmlns="http://webdude.eu/students.xsd"
    xmlns:mstns="http://webdude.eu/students.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="students">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="student">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string" />
              <xs:element name="sex" type="xs:string" />
              <xs:element name="birthdate" type="xs:dateTime" />
              <xs:element name="phone" type="xs:decimal" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="course" type="xs:string" />
              <xs:element name="speciality" type="xs:string" />
              <xs:element name="facultyNumber" type="xs:unsignedInt" />
              <xs:element name="takenExams">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="exam">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="name" type="xs:string" />
                          <xs:element name="tutor" type="xs:string" />
                          <xs:element name="score" type="xs:byte" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="enrollmentInformation">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="date" type="xs:string" />
                    <xs:element name="score" type="xs:unsignedByte" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="endorsements">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="endorsement">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="courseName" type="xs:string" />
                          <xs:element name="certified" type="xs:boolean" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hrist0stoichev/Telerik-Homeworks/Databases/XML Basics/students.xml
<?xml version="1.0" encoding="utf-8" ?>
<students
  xmlns="urn:students"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:students students.xsd"
  name="List Of Students">
  <student>
    <name>Dimo Petrov</name>
    <sex>Male</sex>
    <birthdate>17/04/1984</birthdate>
    <phone>08886022377</phone>
    <email>dimo.petrov@telerik.com</email>
    <course>JS Applications</course>
    <speciality>IT</speciality>
    <facultyNumber>123456</facultyNumber>
    <takenExams>
      <exam>
        <name>JS Applications</name>
        <tutor>DonchoMinkov</tutor>
        <score>64</score>
      </exam>
      <exam>
        <name>JS DOM and UI</name>
        <tutor>DonchoMinkov</tutor>
        <score>189</score>
      </exam>
    </takenExams>
  </student>
</students>
